// JsFromRoutes CacheKey 3afe3d0c9c11fb640a018190fd25c891
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  get: definePathHelper('get', '/profile'),
}
