// JsFromRoutes CacheKey 7da0a0e3473b58a706aba0d07ca702a8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: definePathHelper('get', '/sign_up'),
}
