// JsFromRoutes CacheKey 62bb37bcb3124c849ce3c5193647b51b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  destroy: definePathHelper('get', '/logout'),
}
