// JsFromRoutes CacheKey 40600a5d6d88577bf1cddf03254b9481
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: definePathHelper('get', '/auth/unblock/new'),
  get: definePathHelper('get', '/auth/unblock'),
  create: definePathHelper('post', '/auth/unblock'),
}
