require:
  - 'rubocop-rails'
  - 'rubocop-rspec'
  - 'rubocop-factory_bot'

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'docs/**/*'
    - 'config/puma.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 3.3

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: true

Layout/LineLength:
  Max: 120

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'config/**/*'
    - '**/*.rake'
    - '**/routes.rb'
    - 'spec/**/*.rb'
    - 'integrations/**/Rakefile'
    - 'integrations/**/*.rake'
    - 'integrations/**/spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'config/**/*'
    - 'app/queries/**/*.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'bin/bundle'
    - '**/*_query.rb'
  AllowedMethods:
    - as_json

Metrics/AbcSize:
  Max: 30

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Include:
    - 'spec/**/*'

Rails/Output:
  Exclude:
    - 'config/**/*'

Rails/SkipsModelValidations:
  Exclude:
    - '**/*_spec.rb'

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/MessageSpies:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

RSpec/NestedGroups:
  Max: 4

RSpec/ContextWording:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false
