import { library } from '@fortawesome/fontawesome-svg-core';

import {
  faArrowDownAZ,
  faAt,
  faBrazilianRealSign,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleInfo,
  faDollarSign,
  faEllipsisVertical,
  faEuroSign,
  faFilter,
  faFloppyDisk,
  faGear,
  faKey,
  faList,
  faPenToSquare,
  faPlus,
  faRightFromBracket,
  faRightToBracket,
  faShapes,
  faShareNodes,
  faSterlingSign,
  faSquareMinus,
  faSquarePlus,
  faTrashCan,
  faTriangleExclamation,
  faUser,
  faUserPlus,
  faUserTag,
  faWallet,
  faYenSign,
} from '@fortawesome/free-solid-svg-icons';

import {
  faCircleCheck as farCircleCheck,
  faCircleQuestion as farCircleQuestion,
  faCircleXmark as farCircleXmark,
  faFaceFrown as farFaceFrown,
  faSquareMinus as farSquareMinus,
} from '@fortawesome/free-regular-svg-icons';

library.add(
  faArrowDownAZ,
  faAt,
  faBrazilianRealSign,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  farCircleCheck,
  faCircleInfo,
  farCircleQuestion,
  farCircleXmark,
  faDollarSign,
  faEllipsisVertical,
  faEuroSign,
  farFaceFrown,
  faFilter,
  faFloppyDisk,
  faGear,
  faKey,
  faList,
  faPenToSquare,
  faPlus,
  faRightFromBracket,
  faRightToBracket,
  faShapes,
  faShareNodes,
  faSterlingSign,
  faSquareMinus,
  farSquareMinus,
  faSquarePlus,
  faTrashCan,
  faTriangleExclamation,
  faUser,
  faUserPlus,
  faUserTag,
  faWallet,
  faYenSign,
);
