import { library } from '@fortawesome/fontawesome-svg-core';

import {
  faArrowDownAZ,
  faAt,
  faBan,
  faBrazilianRealSign,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleInfo,
  faDollarSign,
  faEllipsisVertical,
  faEquals,
  faEuroSign,
  faFilter,
  faFloppyDisk,
  faGear,
  faHome,
  faKey,
  faList,
  faMinus,
  faPenToSquare,
  faPlus,
  faRepeat,
  faRightFromBracket,
  faRightToBracket,
  faRotateLeft,
  faScaleBalanced,
  faShapes,
  faShareNodes,
  faSpinner,
  faSterlingSign,
  faSquareCheck,
  faSquareMinus,
  faSquarePlus,
  faTriangleExclamation,
  faUser,
  faUserPlus,
  faUserTag,
  faWallet,
  faXmark,
  faYenSign,
} from '@fortawesome/free-solid-svg-icons';

import {
  faCircleCheck as farCircleCheck,
  faCircleQuestion as farCircleQuestion,
  faCircleXmark as farCircleXmark,
  faCreditCard as farCreditCard,
  faFaceFrown as farFaceFrown,
  faFolder as farFolder,
  faSquare as farSquare,
  faSquareMinus as farSquareMinus,
  faTrashCan as farTrashCan,
} from '@fortawesome/free-regular-svg-icons';

import {
  faGithub as fabGithub,
} from '@fortawesome/free-brands-svg-icons';

library.add(
  faArrowDownAZ,
  faAt,
  faBan,
  faBrazilianRealSign,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  farCircleCheck,
  faCircleInfo,
  farCircleQuestion,
  farCircleXmark,
  farCreditCard,
  faDollarSign,
  faEllipsisVertical,
  faEquals,
  faEuroSign,
  farFaceFrown,
  faFilter,
  faFloppyDisk,
  farFolder,
  faGear,
  fabGithub,
  faHome,
  faKey,
  faList,
  faMinus,
  faPenToSquare,
  faPlus,
  faRepeat,
  faRightFromBracket,
  faRightToBracket,
  faRotateLeft,
  faScaleBalanced,
  faShapes,
  faShareNodes,
  faSpinner,
  faSterlingSign,
  farSquare,
  faSquareCheck,
  faSquareMinus,
  farSquareMinus,
  faSquarePlus,
  farTrashCan,
  faTriangleExclamation,
  faUser,
  faUserPlus,
  faUserTag,
  faWallet,
  faXmark,
  faYenSign,
);
