// JsFromRoutes CacheKey 4ee3b3514d883c92f8256d7dbf26793c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: definePathHelper('get', '/auth/verification/new'),
  get: definePathHelper('get', '/auth/verification'),
  create: definePathHelper('post', '/auth/verification'),
}
