// JsFromRoutes CacheKey 0dd2880f3efba2176dd332b11aad6d3d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/auth/secret/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/auth/secret/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/auth/secret'),
  create: /* #__PURE__ */ definePathHelper('post', '/auth/secret'),
}
