// JsFromRoutes CacheKey 8c7f456433641a1bac723de3d9c89ebf
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: definePathHelper('get', '/auth/secret/new'),
  edit: definePathHelper('get', '/auth/secret/edit'),
  update: definePathHelper('patch', '/auth/secret'),
  create: definePathHelper('post', '/auth/secret'),
}
