// JsFromRoutes CacheKey 9389beff0006e7556681fcf77328e86a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  cancel: definePathHelper('get', '/auth/sign_up/cancel'),
  new: definePathHelper('get', '/auth/sign_up/new'),
  edit: definePathHelper('get', '/auth/sign_up/edit'),
  update: definePathHelper('patch', '/auth/sign_up'),
  destroy: definePathHelper('delete', '/auth/sign_up'),
  create: definePathHelper('post', '/auth/sign_up'),
}
