// JsFromRoutes CacheKey 155f3e2fc05b90b1df5e2c5586ce155f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: definePathHelper('get', '/auth/login'),
  create: definePathHelper('post', '/auth/login'),
  destroy: definePathHelper('delete', '/auth/logout'),
}
