// JsFromRoutes CacheKey 5f53ac40b6d5beb8d1e125b72ba6b6d3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/auth/unblock/new'),
  show: /* #__PURE__ */ definePathHelper('get', '/auth/unblock'),
  create: /* #__PURE__ */ definePathHelper('post', '/auth/unblock'),
}
