// JsFromRoutes CacheKey 6119ca663bd4d785e168f7aa1ae6c978
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/account_share_invites_sent'),
  create: /* #__PURE__ */ definePathHelper('post', '/account_share_invites_sent'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/account_share_invites_sent/:id'),
}
