// JsFromRoutes CacheKey 34db907bb80b590c4d48da7b385b080d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/account_share_invites'),
  create: /* #__PURE__ */ definePathHelper('post', '/account_share_invites'),
  new: /* #__PURE__ */ definePathHelper('get', '/account_share_invites/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/account_share_invites/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/account_share_invites/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/account_share_invites/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/account_share_invites/:id'),
}
