// JsFromRoutes CacheKey de262c7e1dde5531125979517d2751cf
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/accounts'),
  create: /* #__PURE__ */ definePathHelper('post', '/accounts'),
  new: /* #__PURE__ */ definePathHelper('get', '/accounts/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/accounts/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/accounts/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/accounts/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/accounts/:id'),
}
