// JsFromRoutes CacheKey 5f5fe9690f3ce6bcdd89486eb8bdb751
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/wallet_share_invites'),
  create: /* #__PURE__ */ definePathHelper('post', '/wallet_share_invites'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/wallet_share_invites/:id'),
}
