// JsFromRoutes CacheKey de262c7e1dde5531125979517d2751cf
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/profiles'),
  create: /* #__PURE__ */ definePathHelper('post', '/profiles'),
  new: /* #__PURE__ */ definePathHelper('get', '/profiles/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/profiles/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/profiles/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/profiles/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/profiles/:id'),
}
