// JsFromRoutes CacheKey 9c922ce2ebb6df893960b03393aa8ab8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  reenable: /* #__PURE__ */ definePathHelper('patch', '/budgets/:id/reenable'),
  index: /* #__PURE__ */ definePathHelper('get', '/budgets'),
  create: /* #__PURE__ */ definePathHelper('post', '/budgets'),
  update: /* #__PURE__ */ definePathHelper('patch', '/budgets/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/budgets/:id'),
}
