// JsFromRoutes CacheKey d8dd2285ca31d6df7d84ceb44bd8286c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  reenable: /* #__PURE__ */ definePathHelper('patch', '/budgets/:id/reenable'),
  index: /* #__PURE__ */ definePathHelper('get', '/budgets'),
  create: /* #__PURE__ */ definePathHelper('post', '/budgets'),
  show: /* #__PURE__ */ definePathHelper('get', '/budgets/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/budgets/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/budgets/:id'),
}
