// JsFromRoutes CacheKey 40caa7c34029249f281143a87da3d374
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/budget_instances'),
}
