// JsFromRoutes CacheKey caf71281a23c2ab68c98e635bfb15ba0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/categories'),
  create: /* #__PURE__ */ definePathHelper('post', '/categories'),
  new: /* #__PURE__ */ definePathHelper('get', '/categories/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/categories/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/categories/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/categories/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/categories/:id'),
}
