// JsFromRoutes CacheKey b4a60ca2ccc2cb05bdfc4787581b3c52
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  reenable: /* #__PURE__ */ definePathHelper('patch', '/categories/:id/reenable'),
  index: /* #__PURE__ */ definePathHelper('get', '/categories'),
  create: /* #__PURE__ */ definePathHelper('post', '/categories'),
  show: /* #__PURE__ */ definePathHelper('get', '/categories/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/categories/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/categories/:id'),
}
