// JsFromRoutes CacheKey 915717a476595ed663fb2bea3892ddc9
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/categories'),
  create: /* #__PURE__ */ definePathHelper('post', '/categories'),
  new: /* #__PURE__ */ definePathHelper('get', '/categories/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/categories/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/categories/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/categories/:id'),
}
