// JsFromRoutes CacheKey dab1f16ae11a2ab88efb348486697514
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/current_accounts'),
}
