// JsFromRoutes CacheKey 7de85700f0cad30725272db230009b17
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/current_profiles'),
}
