// JsFromRoutes CacheKey c906ebe07cddd32da2fbaed8dca0a1db
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/currencies'),
}
