// JsFromRoutes CacheKey ca36070a9bae15ca66fa0113b807ddac
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/currencies'),
}
