// JsFromRoutes CacheKey d4703d47be5f40197da22f43f74288ab
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: definePathHelper('post', '/current_accounts'),
}
