// JsFromRoutes CacheKey b1f566879fb001be7b0fc0f15a83c3a4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/current_profiles'),
}
