// JsFromRoutes CacheKey fd5d33efdc5e4c18ffaaeba88e258c73
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/'),
  dashboard: /* #__PURE__ */ definePathHelper('get', '/dashboard'),
}
