// JsFromRoutes CacheKey 20cc470ea787e4b3757111010682c62f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  get: definePathHelper('get', '/'),
}
