// JsFromRoutes CacheKey 7f68404cd4e23b736ebb873a89837f8c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  get: definePathHelper('get', '/dashboard'),
}
