// JsFromRoutes CacheKey 0a52b3b567fec7ad836b9669a910ae05
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/import_names'),
  create: /* #__PURE__ */ definePathHelper('post', '/import_names'),
  update: /* #__PURE__ */ definePathHelper('patch', '/import_names/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/import_names/:id'),
}
