// JsFromRoutes CacheKey fb58670017328c507afad12558f1bdbe
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/imports/:import_id/import_transactions'),
  update: /* #__PURE__ */ definePathHelper('patch', '/imports/:import_id/import_transactions/:id'),
}
