// JsFromRoutes CacheKey 0b2acc058f1452e814b139071fd16d2f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/imports'),
  create: /* #__PURE__ */ definePathHelper('post', '/imports'),
  show: /* #__PURE__ */ definePathHelper('get', '/imports/:id'),
}
