// JsFromRoutes CacheKey c2a14fa8f5d585e6ea5ce23f581e102c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/imports'),
  create: /* #__PURE__ */ definePathHelper('post', '/imports'),
  show: /* #__PURE__ */ definePathHelper('get', '/imports/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/imports/:id'),
}
