// JsFromRoutes CacheKey 09e5f938145ab59e9cecd50dc8b32c71
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/'),
  landing: /* #__PURE__ */ definePathHelper('get', '/landing'),
}
