// JsFromRoutes CacheKey f60d2318f8870fae5af1d9691bc69f92
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/locales'),
}
