// JsFromRoutes CacheKey 521427d146eae468616ddc67697a068e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/locales'),
}
