// JsFromRoutes CacheKey 2c26a8c65a12cf372dc4049637303f4f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  get: definePathHelper('get', '/profile'),
  update: definePathHelper('patch', '/profile'),
}
