// JsFromRoutes CacheKey 73bbc91de3ee068c86db71cfc2ba8907
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/profile_share_invites_sent'),
  create: /* #__PURE__ */ definePathHelper('post', '/profile_share_invites_sent'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/profile_share_invites_sent/:id'),
}
