// JsFromRoutes CacheKey b42448597f05d04f0943dbb9627ebca3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  reenable: /* #__PURE__ */ definePathHelper('patch', '/profiles/:id/reenable'),
  index: /* #__PURE__ */ definePathHelper('get', '/profiles'),
  create: /* #__PURE__ */ definePathHelper('post', '/profiles'),
  show: /* #__PURE__ */ definePathHelper('get', '/profiles/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/profiles/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/profiles/:id'),
}
