// JsFromRoutes CacheKey dd666c10ebbda9eeb3c46fbd0b37f595
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  finish: /* #__PURE__ */ definePathHelper('patch', '/reconciliations/:id/finish'),
  index: /* #__PURE__ */ definePathHelper('get', '/reconciliations'),
  create: /* #__PURE__ */ definePathHelper('post', '/reconciliations'),
  show: /* #__PURE__ */ definePathHelper('get', '/reconciliations/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/reconciliations/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/reconciliations/:id'),
}
