// JsFromRoutes CacheKey 08621b000b927fd11a63aa2c7efd1594
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/reconciliations/:reconciliation_id/reconciliations_wallets'),
}
