// JsFromRoutes CacheKey 74aeaa078f50b8719a2abc9a7c11a039
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/setting'),
  update: /* #__PURE__ */ definePathHelper('patch', '/setting'),
}
