// JsFromRoutes CacheKey 15990d8d873258574e08b9176c2ba231
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/categories/:category_id/subcategories'),
  create: /* #__PURE__ */ definePathHelper('post', '/categories/:category_id/subcategories'),
  update: /* #__PURE__ */ definePathHelper('patch', '/categories/:category_id/subcategories/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/categories/:category_id/subcategories/:id'),
}
