// JsFromRoutes CacheKey 71fb20ce55516c462544133d8c65f1f2
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/categories/:category_id/subcategories'),
  create: /* #__PURE__ */ definePathHelper('post', '/categories/:category_id/subcategories'),
  new: /* #__PURE__ */ definePathHelper('get', '/categories/:category_id/subcategories/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/categories/:category_id/subcategories/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/categories/:category_id/subcategories/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/categories/:category_id/subcategories/:id'),
}
