// JsFromRoutes CacheKey df5f006b7f2d0052ac5b07269d802b0e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  reenable: /* #__PURE__ */ definePathHelper('patch', '/categories/:category_id/subcategories/:id/reenable'),
  index: /* #__PURE__ */ definePathHelper('get', '/categories/:category_id/subcategories'),
  create: /* #__PURE__ */ definePathHelper('post', '/categories/:category_id/subcategories'),
  update: /* #__PURE__ */ definePathHelper('patch', '/categories/:category_id/subcategories/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/categories/:category_id/subcategories/:id'),
}
