// JsFromRoutes CacheKey bba31d26210e2e575877f06e71944ba4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/transaction_predictions'),
  create: /* #__PURE__ */ definePathHelper('post', '/transaction_predictions'),
  new: /* #__PURE__ */ definePathHelper('get', '/transaction_predictions/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/transaction_predictions/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/transaction_predictions/:id'),
}
