// JsFromRoutes CacheKey 7f0130edbce0659769a60a475a734313
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/transactions'),
  create: definePathHelper('post', '/transactions'),
  new: definePathHelper('get', '/transactions/new'),
  edit: definePathHelper('get', '/transactions/:id/edit'),
  get: definePathHelper('get', '/transactions/:id'),
  update: definePathHelper('patch', '/transactions/:id'),
  destroy: definePathHelper('delete', '/transactions/:id'),
}
