// JsFromRoutes CacheKey 19f77582ad9f392ffab84ac5976cb334
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/transactions'),
  create: /* #__PURE__ */ definePathHelper('post', '/transactions'),
  new: /* #__PURE__ */ definePathHelper('get', '/transactions/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/transactions/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/transactions/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/transactions/:id'),
}
