// JsFromRoutes CacheKey 55694579f7df58bc3bf2e06c5f598851
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/transaction_predictions'),
  create: /* #__PURE__ */ definePathHelper('post', '/transaction_predictions'),
  new: /* #__PURE__ */ definePathHelper('get', '/transaction_predictions/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/transaction_predictions/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/transaction_predictions/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/transaction_predictions/:id'),
}
