// JsFromRoutes CacheKey c6a5c2b4094bf1bd4b737085d49ddd43
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/transaction_automations'),
  create: /* #__PURE__ */ definePathHelper('post', '/transaction_automations'),
  show: /* #__PURE__ */ definePathHelper('get', '/transaction_automations/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/transaction_automations/:id'),
}
