// JsFromRoutes CacheKey 8a56f745d994ea29fe7e697bcbd8037f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/transactions'),
  create: definePathHelper('post', '/transactions'),
  new: definePathHelper('get', '/transactions/new'),
  edit: definePathHelper('get', '/transactions/:id/edit'),
  update: definePathHelper('patch', '/transactions/:id'),
  destroy: definePathHelper('delete', '/transactions/:id'),
}
