// JsFromRoutes CacheKey 35ef41329ec887fafe21cb2494676dba
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/transaction_automations'),
  create: /* #__PURE__ */ definePathHelper('post', '/transaction_automations'),
  update: /* #__PURE__ */ definePathHelper('patch', '/transaction_automations/:id'),
}
