// JsFromRoutes CacheKey 10d2cb6d37ec3eb948a1f02c4fd9032f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/transaction_predictions'),
  new: /* #__PURE__ */ definePathHelper('get', '/transaction_predictions/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/transaction_predictions/:id/edit'),
}
