// JsFromRoutes CacheKey 1bb83d4f202e4bba152bfe7c114d0d2b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/profile_share_invites_received'),
  update: /* #__PURE__ */ definePathHelper('patch', '/profile_share_invites_received/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/profile_share_invites_received/:id'),
}
