// JsFromRoutes CacheKey c80802951d391f0edff6bbf0198f7ebb
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/wallets'),
  create: /* #__PURE__ */ definePathHelper('post', '/wallets'),
  new: /* #__PURE__ */ definePathHelper('get', '/wallets/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/wallets/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/wallets/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/wallets/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/wallets/:id'),
}
