// JsFromRoutes CacheKey 1de3576b23245ae614e29bf94bff7c47
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/wallet_share_invites_sent'),
  create: /* #__PURE__ */ definePathHelper('post', '/wallet_share_invites_sent'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/wallet_share_invites_sent/:id'),
}
