// JsFromRoutes CacheKey b07d4734e36c625d144a2cd5fe462357
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/wallets'),
  create: /* #__PURE__ */ definePathHelper('post', '/wallets'),
  update: /* #__PURE__ */ definePathHelper('patch', '/wallets/:id'),
}
