// JsFromRoutes CacheKey 4e245332747cd599bc2bec7749adac23
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/imports/:import_id/imports/import_transactions'),
  update: /* #__PURE__ */ definePathHelper('patch', '/imports/:import_id/imports/import_transactions/:id'),
}
