// JsFromRoutes CacheKey 91ba1c07490e03cf14e5354764dfe1c7
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  update: /* #__PURE__ */ definePathHelper('patch', '/imports/import_transactions/:id'),
}
