// JsFromRoutes CacheKey 806b2bf10b196b0b2ef81f1a7c16c35c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/imports/setting'),
}
