default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host:     "<%= ENV.fetch('DATABASE_HOST') %>"
  port:     <%= ENV.fetch('DATABASE_PORT') %>
  username: "<%= ENV.fetch('DATABASE_USERNAME') %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD') %>"

development:
  <<: *default
  database: finance_micromanager_development

test:
  <<: *default
  database: finance_micromanager_test

production:
  <<: *default
  database: finance_micromanager_production
