// JsFromRoutes CacheKey 78f8c8850b50ad6fbe2edf9476fb1035
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/statistics/category_summaries'),
}
