# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will build the Dockerfile for the application and push it to the private registry
name: "Build and push Docker image"
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOSTNAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64
          file: deploy/docker/rails.Dockerfile
          tags: |
            ${{ secrets.REGISTRY_HOSTNAME }}/finance_micromanager:${{ github.ref_name }}
            ${{ secrets.REGISTRY_HOSTNAME }}/finance_micromanager:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
