# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will create a new release
name: "Create Release"
on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version Type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
jobs:
  create_release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PAT }}
      - name: Bump VERSION file
        id: bump_version
        run: |
          bin/bump_version ${{ inputs.version_type }}
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Delete existing coverage.csv file
        run: rm spec/coverage.csv
      - name: Download coverage.csv artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.PAT }}
          workflow: rubyonrails.yml
          workflow_conclusion: success
          branch: main
          name: coverage_csv
          path: spec/coverage.csv
      - name: Inject new version tag into coverage.csv
        run: |
          grep -q VERSION spec/coverage.csv; if [ ! $? -eq 0 ]; then exit 1; fi
          sed -i "s/VERSION/v${{ steps.bump_version.outputs.VERSION }}/" spec/coverage.csv
          grep -q v${{ steps.bump_version.outputs.VERSION }} spec/coverage.csv; if [ ! $? -eq 0 ]; then exit 1; fi
      - name: Commit new version and tag
        run: |
          git config --global user.name 'Rodrigo Azevedo'
          git config --global user.email 'roooodcastro@users.noreply.github.com'
          git commit -am "Release v${{ steps.bump_version.outputs.VERSION }}"
          git push origin main
          git tag -a v${{ steps.bump_version.outputs.VERSION }} -m "Release v${{ steps.bump_version.outputs.VERSION }}"
          git push origin v${{ steps.bump_version.outputs.VERSION }}
      - name: Update HEAD
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PAT }}
      - name: Create new Release
        run: |
          gh release create "v${{ steps.bump_version.outputs.VERSION }}" \
            --title="Release ${{ steps.bump_version.outputs.VERSION }}" \
            --latest \
            --generate-notes
